// const windowWidth = $('window').width()
// $('<div>').width(windowWidth).height('50px').appendTo('body')

$(() => {
  // console.log('connected')
  const windowWidth = $(document).width()
  const windowHeight = $(window).height()
  $('<div>').css('width', (windowWidth)).css('height', windowHeight).attr('class', 'header').appendTo('body')
  $('<h2>').html(`Hello! My name is <span>Jeremy Spewock</span> and I am a Full-stack Software Engineer`).attr('id', 'intro-h2').appendTo('div')
  $('<div>').attr('id', 'main').appendTo('body').css('margin-top', (windowHeight + 40))
  $('<div>').attr('id', 'about').appendTo('#main')
  $('<h2>').text('About Me').attr('class', 'section').appendTo('#about')
  $('<p>').text('I am a college undergraduate with a passion and desire to deepen my understanding of computer science. I have a love for solving linear and logical problems and I’m determined to further my knowledge in this field and create powerful user-friendly applications by researching the market and using my ever-expanding skill set to meet the needs of the consumer.').appendTo('#about')
  $('<h3>').html(`Technical Skills`).appendTo('#about').attr('class', 'tech-skills')
  $('<p>').text('HTML | JavaScript | CSS | Python | jQuery | NodeJS | Git |  GitHub | MongoDB | React.js | Postman | Flexbox | Bootstrap | Express.js | REST API | SQL |').attr('class', 'tech-skills').appendTo('#about')
  $('<div>').attr('id', 'projects').appendTo('#main')
  $('<h2>').text('Projects').attr('class', 'section').appendTo('#projects')
  $('<p>').text('{To be filled in later}').appendTo('#projects')
  $('<div>').attr('id', 'contact-me').appendTo('#main')
  $('<h2>').text('Contact Me').attr('class', 'section').appendTo('#contact-me')
})